### ISSUE TITLE
Add event props for palette open and close

### ISSUE THREAD

**Issue by maxbaluev** [asabaylus/react-command-palette#102]

**Comment by asabaylus** [comment]
Can you describe what you want to do? The component my already support your use case.

**Comment by maxbaluev** [comment]
@asabaylus I am use it inside chrome extension, at content script. I am need to detect closing to make some additional actions.

**Comment by asabaylus** [comment]
I don’t mind add an event prop but there’s already the open prop. You can set set the trigger prop to null and externally open / close the palette. LMK if that works for you or you need and example

**Comment by maxbaluev** [comment]
And how, for example, detect closing on ESC ?

**Comment by maxbaluev** [comment]
Component awesome. Please add more events for all possible actions. This is the part that is really missing.

**Comment by asabaylus** [comment]
Good point, I’ll see what I put together for you tonight or tomorrow

**Comment by asabaylus** [comment]
@maxbaluev I'd appreciate if you took a look at this PR #103 which add two new props. I'll see about deploying a new version later tonight if that looks like what you need

**Comment by asabaylus** [comment]
@maxbaluev added in v0.3.0-0
