### ISSUE TITLE
[Question] How to check if input is active/focused

### ISSUE THREAD

**Issue by calebchiam** [asabaylus/react-command-palette#1073]
Hi, I'm using the command palette on a page where keyboard shortcuts are used. I'd like to distinguish those keyboard inputs from those used when typing in the search input of the command palette.

May I ask if there is a good way to do this? From the docs, there doesn't to be a way to check if the input is currently active. One typical solution would be to pass a ref to the input component, but that's not currently exposed by the command palette. (Not that I think it should necessarily be exposed just for this specific use case.) 

Thanks!

**Comment by asabaylus** [comment]
@calebchiam this sounds similar to https://github.com/asabaylus/react-command-palette/issues/455

please let me know if your use case is the same. I’ve been considering making a breaking change to replace mousetrap.js since it’s a dead project. @mminer had raised the subject of useCapture in mousetrap. Would love to get your thoughts

**Comment by calebchiam** [comment]
Interesting! -- I think my use case is actually in the 'opposite' direction; the problem is that my keyboard shortcuts may be alphanumeric (e.g. just the single 'Q' key) and I don't want these shortcuts to trigger when the command palette input is being used. In other words, some component external to the command palette needs to check the state of the input to figure out whether to fire off the keyboard shortcut, so `useCapture` would not been helpful for that if I'm understanding correctly.

**Comment by asabaylus** [comment]
Would the onChange prop work? 

onChange is a function that's called when the input value changes. It returns two values: the current value of the input field followed by the users typed input. The query ignores keyboard navigation and clicks

**Comment by calebchiam** [comment]
The onChange prop doesn't let me know when the input is focused vs blurred (which is the state I'm interested), so it wouldn't be useful here.

But don't worry about it! I ended up implementing a command palette from scratch (borrowing the styling from yours), so this change is not urgently needed from my end anymore. Thank you for responding though, and feel free to close this issue.

**Comment by asabaylus** [comment]
Glad you found a solution
