### ISSUE TITLE
UNSAFE_componentWillReceiveProps in strict mode is not recommended

### ISSUE THREAD

**Issue by unional** [asabaylus/react-command-palette#1137]
**Describe the bug**

Getting this warning when running the code in `React.StrictMode`:

```tsx
<React.StrictMode>
  <CommandPalette ... />
</React.StrictMode>
```

```
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Comment by unional** [comment]
Same issue as #804

**Comment by unional** [comment]
https://github.com/cyberuni/react-command-paletter-strict-mode

Here is the repro. 🌷

**Comment by unional** [comment]
Close as dup of #804 
Caused by https://github.com/moroshko/react-autosuggest/issues/624

**Comment by Mohammed-Q96** [comment]
> https://github.com/cyberuni/react-command-paletter-strict-mode
> 
> Here is the repro. 🌷

The repo is not visible
