### ISSUE TITLE
Add support for React 18

### ISSUE THREAD

**Issue by jdejoode** [asabaylus/react-command-palette#1182]
**Describe the bug**

**To Reproduce**
1. Try to follow the README 
2. npx create-react-app somename
3. npm install react-command-palette
4. sigh because react 18 doesn't play nice with react-command-palette out of the box

**Comment by asabaylus** [comment]
Working on it, unfortunately several years ago when I started this project enzyme was the defacto standard. It looks like enzyme will not be supporting React 18.
