### ISSUE TITLE
Question: Colored labels / categories 

### ISSUE THREAD

**Issue by pcgeek86** [asabaylus/react-command-palette#169]
**Question**: In the Storybook for this component, I noticed that you can add colored labels / categories, as in [this example](https://react-command-palette.js.org/?path=/story/command-palette--with-multiple-highlights). However, I can't seem to see the source code in Storybook, so I'm not sure how to implement these categories.

Could we add this to the documentation? I'm happy to write something up, if you show me how to do it.

**Comment by asabaylus** [comment]
@pcgeek86 you can use the renderCommand prop. Here's a full example: https://github.com/asabaylus/react-command-palette/blob/master/examples/sampleChromeTheme.md

Along with the associated codesandbox so you can see it in action:
https://codesandbox.io/s/reactcommandpalette-with-chrome-theme-gfx7l?fontsize=14

Please let me know if this is what you're looking for

**Comment by pcgeek86** [comment]
Yes, that's exactly it! Thank you. I will try to write something up and send a PR to update the README soon.
