### ISSUE TITLE
How do I route to a page using react-router-dom

### ISSUE THREAD

**Issue by sudhamab** [asabaylus/react-command-palette#254]
**Is your feature request related to a problem? Please describe.**
Hi, firstly, great job with the command palette. I was able to adapt it to look exactly like I wanted. However, I am trying to figure out how I can create a "command" for each option so each may either navigate to a different component using react-router-dom, or then open up another modal for example on the same screen ?

**Describe the solution you'd like**
Would be good if I could do something like 
`<Link to="/login"/>`

**Describe alternatives you've considered**
It works if I do 
`document.location.href = 'http://localhost:3000'`

but I plan to embed my react app inside Electron to make a desktop app. .

Could you please advise?

**Comment by sudhamab** [comment]
the following worked for me
`document.location.href = '/'`
so i guess no need for the react-dom-router?

**Comment by asabaylus** [comment]
@sudhamab please checkout history.push 
https://tylermcginnis.com/react-router-programmatically-navigate/

I’d suggest calling it from with the commands. Please LMK if this is what you’re looking for and I’ll close the ticket

**Comment by sudhamab** [comment]
thanks @asabaylus . I looked at that reference you mentioned before reaching out. But somehow i am not able to call the setState method so I am probably missing something syntactical. 

Ideally i'd like to structure the code as in the example 
https://codesandbox.io/s/hfqjn 
where the styling and the component and the commands are nicely separated. 
But even if I put things inline like the code below, I am not able to call the setState 

```
import React from 'react'
import atomTheme from "./atomTheme"
import atomCommand from "./atomCommand"
import "./atomTheme.css"
import CommandPalette from 'react-command-palette'

class CustomCommandPalette extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      currentCommand: ''
    }
    this.handleSubmit = this.handleSubmit.bind(this)
  }

  handleSubmit = (shortcut) => {
    console.log('handleSubmit')
    this.setState({currentCommand: shortcut})
  }

  commands = [
    {
      id: 1,
      name: "Go to Home Screen",
      category: "Navigate",
      shortcut: "H",
      // command: function noRefCheck() {
      //   this.handleSubmit(this.shortcut)
      // }
      command() {
        return () => this.handleSubmit(this.shortcut)
      }
    }
  ]

  render() {
    console.log('render was called')
    return(
      <CommandPalette
        hotKeys="command+k"
        renderCommand={atomCommand}
        theme={atomTheme}
        commands={this.commands}
        trigger={"click me"}
        // closeOnSelect={true}  /*IMPORTANT: REMEMBER TO CHANGE BACK LATER */
        open
      />
    )
  }
}

export default CustomCommandPalette;
```

If you can show me how I can provide the setState option if the commands file is separate, that would be perfect. 
Else, at least knowing how I can do this in the component class would be useful. 

thanks in advance!

**Comment by asabaylus** [comment]
To quote the ReadMe: The command is a function that will be executed when the user clicks or presses the enter key. Commands may also include custom properties where "this" will be bound to the command, for example:

`
  {
    id: 1,
    color: 'pink',
    name: "Foo",
    command() {
      document.location.href = `somepage.html?id=${this.id}&color=${this.color}`;
    }
  },
  ...
`
The this is you method is bound to the scope of the command itself.

**Comment by asabaylus** [comment]
@sudhamab did you figure it out, or do you need an example?

**Comment by sudhamab** [comment]
@asabaylus thank you for following up. actually an example would be great but ideally if you could guide me how to do it with the commands in a separate file that would be great. but if not, whatever you think is the right way to structure the code. we want to keep it clean. 

I know in my example, the this was referring only to the keys within the command but I shared it anyways to share with you what I was trying to do so you can guide me 

much appreciate your follow up and help. 

definitely going to use your command palette in our project. 

thanks again

**Comment by asabaylus** [comment]
You can do something like...

```
function command() {
  console.log(`Run Command: ${this.id} 
  with payload ${JSON.stringify(this)}`);
}

export default [
  {
    id: 1,
    category: "Command",
    color: "purple",
    name: "Start All Data Imports",
    command
  },
  ...

// Run Command: 1 
//  with payload {"id":1,"category":"Command","color":"purple","name":"Start All Data Imports"} 
```
Checkout the commands.js file:
https://codesandbox.io/embed/reactcommandpalette-t1lyh?expanddevtools=1&fontsize=14&hidenavigation=1&moduleview=1

**Comment by sudhamab** [comment]
@asabaylus sincere apologies for the delay. I was trying to integrate other pieces of the app in the mean time.  and thank you for sharing the example. 

But I am trying to still figure out how to use the command field to "navigate / route" to a different path in the app. 

the new addition to this problem is that I am trying this in an Electron app. So document.location.href worked if I use a  BrowerRouter but not HashRouter. 

If I could somehow pass information back to parent component once the command is selected, it would be good. An onSelect() handler that lets me then interpret the selected value. So then I could use the parent component for navigation.

**Comment by asabaylus** [comment]
@sudhamab While I’m pretty sure you can achieve your goal without onSelect I’ve been considering adding it for a while now. iWork on it next

**Comment by sudhamab** [comment]
thank you. yes please add onSelect at your earliest convenience. We want to roll out one beta version and we are just waiting to resolve this. 

 I am trying other ways but this would make life much easier and with the onSelect we can probably use things like "Link" or something like it to redirect based on which option is selected. without it i am still figuring it out. 

Also this library is a crucial one for what we are building. thanks once again.

**Comment by sudhamab** [comment]
@asabaylus after trying a bunch of different things, I was able to find a work around in the following way by using `withRouter`.  I have not yet packaged it into a DMG but this feels like progress. Thought i should share it  

```
import React from 'react'
import commands from "./commands"
import atomTheme from "./atomTheme"
import atomCommand from "./atomCommand"
import "./atomTheme.css"
import CommandPalette from 'react-command-palette'
import { withRouter } from "react-router";

var selectedIndex = 0;

class CustomCommandPaletteWithoutRouter extends React.Component {

  constructor(props) {
    super(props)
    this.state = {
      selectedIndex: 0,
      commands: [
        {
          id: 2,
          name: "Do something",
          category: "Command",
          shortcut: 'M',
          command() {props.history.push('/do/something')}
        },
        {
          id: 3,
          name: "Do Something Else",
          category: "Command",
          shortcut: 'B',
          command() {props.history.push('/do/another/thing')}
        }
      ]
    }
  }

 

  render() {
    return(
      <CommandPalette
        hotKeys= 'command+k'
        renderCommand={atomCommand}
        theme={atomTheme}
        commands={this.state.commands}
        trigger={"click me"}
        maxDisplayed={100}
        open
      />
    )
  }
}

const CustomCommandPalette = withRouter(CustomCommandPaletteWithoutRouter)

export default CustomCommandPalette
```

**Comment by asabaylus** [comment]
@sudhamab thank for posting that solution, looks good to me. Also I’ve added and onSelect event if you need it

**Comment by sudhamab** [comment]
thank you @asabaylus for adding this! we will refactor our code to use onSelect as soon as we get a chance.
