### ISSUE TITLE
Cannot see all commands on scroll

### ISSUE THREAD

**Issue by sudhamab** [asabaylus/react-command-palette#257]
**Describe the bug**
Hi Team, 

thanks for this brilliant library. I am facing one issue. I believe the default number of entries in the suggestionsList is 7, but even when I tried to override it, it shows only 7. So after the 7th position, it shows the suggestion at the 1st position again and keeps cycling through 

However, if I search for an item which is outside the 1st 7 options, it does show up correctly

**Expected behavior**
I am looking for a way so that even though there may be only 7 suggestions on display, i can keep scrolling down to see all commands

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome

**Comment by asabaylus** [comment]
You may want to double check your data. The component won’t “wrap” the displayed commands. When the user scrolls to the bottom the last command is displayed and the user must scroll back to the top to see the first command.

So if you’re seeing the commands cycling there’s very probably dupes in your data. Please make sure your commands are unique. The command palette simply renders what’s present in your list, there’s no magic

**Comment by sudhamab** [comment]
thanks @asabaylus . I have provided unique ids (30 of them ) and the shortcut keys are also all different. I have not put in call the command functions  yet it's a WIP and will take longer. 

Should the id field being unique along with unique shortcut not suffice?

**Comment by sudhamab** [comment]
Also, wanted to add that i looked at the sample here
https://codesandbox.io/s/hfqjn

even here, if you scroll through the options, it shows only 7 items.

**Comment by asabaylus** [comment]
Try setting _maxDisplayed_ to a number greater than the available vertical space, ex: `maxDisplayed={100}`. Then set...

```
/* atomTheme.css */

.atom-suggestionsContainerOpen {
  overflow: auto;
  ...
```

Here's an example
https://codesandbox.io/s/react-command-palette-with-atom-theme-2qb4m?fontsize=14

Beware of browser performance limits.

**Comment by sudhamab** [comment]
thanks @asabaylus!  Yes this works. Appreciate the prompt revert.
