### ISSUE TITLE
Add an onSelect event

### ISSUE THREAD

**Issue by asabaylus** [asabaylus/react-command-palette#316]
**Is your feature request related to a problem? Please describe.**
I want the command pallet to raise an onSelect event when the user makes their selection

**Describe the solution you'd like**
It should trigger a callback event when the user select an item.
The event payload should contain the item selected

**Comment by sudhamab** [comment]
@asabaylus  is this likely soon (this week)? We have spent quite a bit of time trying to make this work so would be great if this happens. thank you again

**Comment by asabaylus** [comment]
@sudhamab try v0.5.0-0 you'll have access to a new prop onSelect.

```
    <ReactCommandPalette
      renderCommand={atomCommand}
      theme={atomTheme}
      commands={commands}
      onSelect={(suggestion)=>{
        alert(`${JSON.stringify(suggestion)}`)
      }}
      open
    />
```
