### ISSUE TITLE
Allow clearing query on close

### ISSUE THREAD

**Issue by mminer** [asabaylus/react-command-palette#454]
**Is your feature request related to a problem? Please describe.**
After closing the command palette (whether normally or by selecting a command) and reopening it, the input contains the previous query.

**Describe the solution you'd like**
Either change the default behaviour so that the `<input>` clears when the command palette closes, or make it an option, e.g. a `clearInputOnClose` prop.

**Describe alternatives you've considered**
Could probably clear the input manually with some `findDOMNode` hackery, but not an ideal solution.

**Additional context**
I notice that the behaviour of the Chrome DevTools command palette is to clear the input on close.

**Comment by mminer** [comment]
Also, happy to submit a PR for either change (clearing by default or `clearInputOnClose` prop).

**Comment by asabaylus** [comment]
@mminer id think the solution you proposed to clearInputOnClose where the default is to retain the current input would make a great addition. Please feel free to submit a PR.

**Comment by asabaylus** [comment]
PR #456 accepted ships in v0.10.0-0
