### ISSUE TITLE
How do you implement subcommand menus?

### ISSUE THREAD

**Issue by calvinwyoung** [asabaylus/react-command-palette#498]
**Is your feature request related to a problem? Please describe.**

What's the best way to implement subcommand menus? Specifically, I'd like the following behavior:

1. User opens command palette, sees 2 options: "Foo" and "Bar"
2. If the user selects "Foo", the command palette closes, and the "Foo" command executes.
3. If the user selects "Bar", the command palette stays open, and shows another set of commands that the user can select from.

I saw the conversation at #362, as well as the [example here](https://codesandbox.io/s/react-command-palette-dynamic-lists-p2xo9). It seems like I can mostly get what I want by adding some logic to the `onSelect` callback that generates a new set of `commands`.

The one problem I can't figure out is how to keep the command palette open after selecting the "Bar" command (from the example above). I could toggle a state variable on `onSelect` that changes the `closeOnSelect` prop, but unfortunately that doesn't seem to work.

What's the recommended approach here?

**Describe the solution you'd like**

Some way to selectively keep the command palette open based on the selected command.

**Describe alternatives you've considered**

This unfortunately does not work:

```javascript
export const Example = () => {
  const [commands, setCommands] = useState([...]);
  const [closeOnSelect, setCloseOnSelect] = useState(true);

  return (
    <CommandPalette
      closeOnSelect={closeOnSelect}
      commands={commands}
      onSelect={(command) => {
        if (<should get subcommands>) {
          setCommands(<get subcommands>);
          setCloseOnSelect(false);
        } else {
          setCloseOnSelect(true);
        }
      }}
    />
  );
};
```

**Comment by asabaylus** [comment]
@calvinwyoung if memory serves, setting `closeOnSelect` to false should do the trick. If it doesn’t or you want an example please LMK, I’m pretty close to landing the VS Code theme which does exactly what you want but the docs aren’t ready

**Comment by calvinwyoung** [comment]
Great, thank you! I'll go aheand and close this issue, and will wait for you to have a chance to update the docs.

**Comment by asabaylus** [comment]
@calvinwyoung after poking around I think `open` should mage the display of the component anytime it’s changed. I hadn’t envisioned this use case. I’ll go ahead and put this on the top of my queue. Thanks for raising this issue.

**Comment by calvinwyoung** [comment]
@asabaylus Awesome, thanks so much!

**Comment by asabaylus** [comment]
@calvinwyoung I've been swamped at work and this issue is next on my list I hope to have something soon but it looks like I may need to fix a bug.
