### ISSUE TITLE
Unable to use in NextJS as global CSS cannot be imported from within node_modules

### ISSUE THREAD

**Issue by popey456963** [asabaylus/react-command-palette#602]
**Describe the bug**
Unable to use in NextJS as global CSS cannot be imported from within node_modules

**To Reproduce**
1. Setup a NextJS project (e.g. `npx create-next-project test`)
2. Import `react-command-palette`
3. Observe failure

**Expected behavior**
It can be imported.

**Comment by asabaylus** [comment]
@popey456963 try [v0.13.1-0](https://github.com/asabaylus/react-command-palette/releases/tag/v0.13.1-0) until I can address this issue. Please LMK if that works for you

**Comment by popey456963** [comment]
Can confirm that v0.13.1-0 does not fix this issue for us.  For now I've fixed it by cloning the repository locally and commenting out both places (atom theme & spinner theme) that import CSS.

Could you fix this by putting the CSS imports behind a component flag (e.g. `importCss={false}`)?

First time using React / NextJS so not super confident how this all works, :)

**Comment by asabaylus** [comment]
I'll take a look at it shortly thanks

**Comment by asabaylus** [comment]
@popey456963 this issue should be resolved with v0.16.0. Nothing special for you do just bump the version of react-command palette. I setup a codesandbox for NextJS here: https://codesandbox.io/s/hungry-mclean-6g6fc?file=/pages/index.js

Please LMK if this resolves your issue.
