### ISSUE TITLE
Integrate ability to run on Windows OS

### ISSUE THREAD

**Issue by wilkinsonjack1993** [asabaylus/react-command-palette#88]
Currently this library does not run on Windows. This is because the scripts in the package.json that refer set the NODE_ENV variable should call 'set NODE_ENV' to work on windows. To get this to work on all operating systems, you can use [cross-env](https://github.com/kentcdodds/cross-env).

**Comment by asabaylus** [comment]
@wilkinsonjack1993 are you making an electron or react native app? I'm not too familiar with these or the context of the issue but will check into it

**Comment by asabaylus** [comment]
@wilkinsonjack1993 please review #89 and LMK if this works for you.
