### ISSUE TITLE
Allow clearing input on select

### ISSUE THREAD

**Issue by tiamed** [asabaylus/react-command-palette#985]
**Is your feature request related to a problem? Please describe.**
When selecting a sub command, the input value need to be cleared

**Describe the solution you'd like**
Allow clearing input on selection

**Describe alternatives you've considered**
Allow changing input value manually

**Comment by asabaylus** [comment]
Hi @tiamed if you leave me an example I'll let you know if clearing is possible

**Comment by tiamed** [comment]
> Hi @tiamed if you leave me an example I'll let you know if clearing is possible

For example, I select `System Preference` option, and therefore the palette displays sub options under `System Preference`. The input value then need to be cleared after this selection, in order to search the sub option.

**Comment by asabaylus** [comment]
@tiamed I think I've got an example thats pretty close to what you're asking for. Here's an example of using a parent list of commands to filter a child list.

https://codesandbox.io/s/react-command-palette-subcommands-gw1zy

In this example the selected / highlighted command is displayed in the search input field which improves a11y and still permits the user to type a new search keyword.

Please LMK if this meets your need

**Comment by tiamed** [comment]
> @tiamed I think I've got an example that's pretty close to what you're asking for. Here's an example of using a parent list of commands to filter a child list.
> 
> https://codesandbox.io/s/react-command-palette-subcommands-gw1zy
> 
> In this example the selected / highlighted command is displayed in the search input field which improves a11y and still permits the user to type a new search keyword.
> 
> Please LMK if this meets your need

In this example the input after first selection is persisted instead of cleared.
